/*
 * Copyright (c) 2015
 *
 * RagingBull. All rights reserved
 */

package com.medic.ragingbull.core.constants;

/**
 * Created by Vamshi Molleti
 */
public enum LocationSpeciality {

    ALLERGOLOGY‎, ANDROLOGY‎, ANESTHESIA‎, ANGIOLOGY‎, AVIATIONMEDICINE‎, BIOMEDICINE‎, CARDIOLOGY‎, DENTISTRY‎, DENTISTRYBRANCHES‎, DISASTERMEDICINE‎, SPORTSPHYSICIANS‎, EMERGENCYMEDICINE‎, ENDOCRINOLOGY‎, FAMILYMEDICINE‎, FICTIONALMEDICALSPECIALISTS‎, GASTROENTEROLOGY‎, GENERALPRACTICE‎, MEDICALGENETICS‎, GERIATRICS‎, GERONTOLOGY‎, GYNAECOLOGY‎, HEMATOLOGY‎, HEPATOLOGY‎, IMMUNOLOGY‎, INFECTIOUSDISEASES‎, INTENSIVECAREMEDICINE‎, INTERNALMEDICINE‎, MENSHEALTH‎, MILITARYMEDICINE‎, NEPHROLOGY‎, NEUROLOGY‎, NUCLEARMEDICINE‎, OBSTETRICS‎, ONCOLOGY‎, OPHTHALMOLOGY‎, OTORHINOLARYNGOLOGY‎, PALLIATIVEMEDICINE‎, PATHOLOGY‎, PEDIATRICS‎, PODIATRY‎, PREVENTIVEMEDICINE‎, PRISONMEDICINE‎, PSYCHIATRICSPECIALITIES‎, PSYCHIATRY‎, PULMONOLOGY‎, RADIOLOGY‎, REHABILITATIONMEDICINE‎, RHEUMATOLOGY‎, SEROLOGY‎, SEXUALHEALTH‎, SLEEPMEDICINE‎, SPACEMEDICINE‎, SPORTSMEDICINE‎, SURGERY‎, SURGICALSPECIALTIES‎, TOXICOLOGY‎, TRANSPLANTATIONMEDICINE‎, TRICHOLOGY‎, TROPICALMEDICINE‎, UROLOGY‎, WILDERNESSMEDICINE‎
}
